CF-611: Refactoring for keyless bootstrapping
metro-digital/terraform-google-cf-projectcfg pull request #29
Opened 2022-06-13 15:30 UTC by cschroer

2022-06-14 09:43 UTC, DatMicha requested changes
Haven't run the script, but found trivial improvements.

2022-06-14 09:43 UTC, DatMicha commented on bootstrap/bootstrap.sh
> +	Once you reviewed the generated Infrastucre as Code configuration, the script supports to automaticly import
```suggestion
	Once you reviewed the generated Infrastructure as Code configuration, the script supports to automatically import
```

2022-06-14 09:43 UTC, DatMicha commented on bootstrap/bootstrap.sh
> +	the generaded resources into the terraform state. THis resouces include:
```suggestion
	the generadet resources into the terraform state. This includes the following resouces:
```

2022-06-14 09:43 UTC, DatMicha commented on bootstrap/bootstrap.sh
> +		${TEXT_COLOR_MAGENTA}You may need to import the resouces manual your state:${TEXT_ALL_OFF}
```suggestion
		${TEXT_COLOR_MAGENTA}You may need to import the resources manually into your state:${TEXT_ALL_OFF}
```

2022-06-14 09:43 UTC, DatMicha commented on bootstrap/bootstrap.sh
> +		The script has done all the initial bootstrapping to execure terraform for the first time!
```suggestion
		The script has done all the initial bootstrapping to execute terraform for the first time!
```

2022-06-14 09:43 UTC, DatMicha commented on bootstrap/bootstrap.sh
> +		The module will create a lot of additional resources at the first run, depending on your configuration:
```suggestion
		The module will create several additional resources during the first run, depending on your configuration:
```

2022-06-14 09:43 UTC, DatMicha commented on bootstrap/templates/project.tf.in
> +          # Allow manager group ti impersonate IaC service account
```suggestion
          # Allow manager group to impersonate IaC service account
```

2022-07-12 09:17 UTC, mariuskiessling approved these changes
lgtm

Thank you for all the work!

2022-07-12 09:18 UTC, merged